version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_with_spring_boot_erudio
      MYSQL_USER: erudio
      MYSQL_PASSWORD: erudio
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb: